# hsbo_logging.yaml

script:
  hsbo_log_event:
    alias: "HSBO Logging Event"
    fields:
      level:
        description: "Log level (debug, info, warning, error)"
        example: "info"
      message:
        description: "Message to log"
        example: "Test message"
      component:
        description: "Component name"
        example: "Battery Management"
    sequence:
      - variables:
          # Check if the file notification entity exists
          logging_enabled: "{{ states('input_boolean.hsbo_logging_enabled') == 'on' }}"
      - choose:
          # If file logging is available
          - conditions: "{{ logging_enabled }}"
            sequence:
              - service: notify.send_message
                data:
                  entity_id: notify.file_hsbo_system_log
                  message: '{"{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}", "{{ level | upper }}", "{{ component }}", "{{ message }}"}'
          # Fallback to system_log
        default:
          - service: system_log.write
            data:
              message: "[{{ component }}] {{ message }}"
              level: "{{ level }}"
              logger: "hsbo"

  hsbo_log_information:
    alias: "HSBO Logging Information"
    fields:
      level:
        description: "Log level (debug, info, warning, error)"
        example: "info"
      message:
        description: "Message to log"
        example: "Test message"
      component:
        description: "Component name"
        example: "Battery Management"
    sequence:
      - variables:
          # Check if the file notification entity exists
          logging_enabled: "{{ states('input_boolean.hsbo_logging_enabled') == 'on' }}"
      - choose:
          # If file logging is available
          - conditions: "{{ logging_enabled }}"
            sequence:
              - service: notify.send_message
                data:
                  entity_id: notify.file_hsbo_system_log
                  message: | 
                    { 
                      "timestamp": "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}", 
                      "level": "{{ level | upper }}", 
                      "component": "{{ component }}", 
                      "message": "{{ message }}" 
                    }

          # Fallback to system_log
        default:
          - service: system_log.write
            data:
              message: "[{{ component }}] {{ message }}"
              level: "{{ level }}"
              logger: "hsbo"


# Test automation
automation:
  - id: hsbo_test_logging_event
    alias: "HSBO Test Logging Event"
    trigger:
      - platform: homeassistant
        event: start
    condition: []
    action:
      - delay:
          minutes: 5
      - service: script.hsbo_log_event
        data:
          level: "info"
          component: "Test Component"
          message: "This is a test log message"
    mode: single
  
  # Rotate log file automation when its surpasses 5 MB
  - id: hsbo_rotate_log_file
    alias: "HSBO Rotate Log File"
    trigger:
      - platform: numeric_state
        entity_id: sensor.hsbo_log_file_size
        above: 5000000  # Trigger if file is above 5 MB aka 5000000 bytes
    condition:
      - condition: state
        entity_id: input_boolean.hsbo_logging_enabled
        state: "on"  # Only run if logging is enabled
    action:
      - action: shell_command.rotate_hsbo_log_file
    mode: single

# sensor:
#   - platform: command_line
#     name: hsbo_log_file_size
#     command: 'stat -c %s /config/hsbo_logging/hsbo_system.log'
#     unit_of_measurement: "bytes"
#     scan_interval: 60  # Polls every 60 seconds, adjust as needed

# shell_command:
#   rotate_hsbo_log_file: "mv /config/hsbo_logging/hsbo_system.log /config/hsbo_logging/hsbo_system_$(date +'%Y%m%d%H%M%S').log && touch /config/hsbo_logging/hsbo_system.log && find /config/hsbo_logging -name 'hsbo_system_*.log' -mtime +30 -exec rm {} \\;"